name: Android CI

on:
  push:
  pull_request:


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Execute unit tests
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

    # Execute instrumented test
    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest
