name: Android CI

on:
  push:
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

        - name: Run Tests
          run: ./gradlew test

        - name: Buld Project
           run: ./gradlew assemble

  #   - name: Grant execute permission for gradlew
  #     run: chmod +x gradlew
  #   - name: Build with Gradle
  #     run: ./gradlew build

  # test:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Run Tests
  #       uses: ReactiveCircus/android-emulator-runner@v2
  #       with:
  #         api-level: 34
  #         target: google_apis
  #         arch: x86_64
  #         script: ./gradlew connectedCheck
