name: Android CI

on:
  push:
  pull_request:


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

#      # Run linter
#    - name: Linter
#      run: ./gradlew lint

    # - name: Unit tests
    #   run: bash ./gradlew test --stacktrace

      
    # # - name: Unit tests results
    # #   uses: actions/upload-artifact@v1
    # #   with:
    # #     name: unit-tests-results
    # #     path: app/build/reports/tests/testDebugUnitTest/index.html

    # - name: Buld Project
    #   run: ./gradlew assemble

  #   - name: Grant execute permission for gradlew
  #     run: chmod +x gradlew
  #   - name: Build with Gradle
  #     run: ./gradlew build

  # test:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Run Tests
  #       uses: ReactiveCircus/android-emulator-runner@v2
  #       with:
  #         api-level: 34
  #         target: google_apis
  #         arch: x86_64
  #         script: ./gradlew connectedCheck
